# list of constants


USER_STATUS_ACTIVE = 'ACTIVE'
USER_STATUS_INACTIVE = 'INACTIVE'


USER_ROLE_PUBLIC = 'PUBLIC'
USER_ROLE_AGENCY = 'AGENCY'
USER_ROLE_ADMIN = 'ADMIN'


# Log codes
LOG_EMAIL_NOT_FOUND = 'EMAIL_NOT_FOUND'
LOG_INCORRECT_PASSWORD = 'INCORRECT_PASSWORD'
LOG_EMAIL_ALREADY_IN_SYSTEM = 'EMAIL_ALREADY_IN_SYSTEM'


# codes
ALERT_INCORRECT_CREDENTIALS = 'INCORRECT_CREDENTIALS'
ALERT_EMAIL_ALREADY_REGISTERED = 'EMAIL_ALREADY_REGISTERED'
ALERT_LOGGED_OUT = 'LOGGED_OUT'


# routes
ROUTE_FRONT = 'FRONT'
ROUTE_LOGIN = 'LOGIN'
ROUTE_REGISTER = 'REGISTER'
ROUTE_LOGOUT = 'LOGOUT'

ROUTE_CONTENT = 'CONTENT'
ROUTE_CONTENT_WITH_ID = 'CONTENT_WITH_ID'
